name: Re-run 2 Add Rules to Cloudflare Gateway 
on:
  workflow_run:
    workflows: ["Re-run Add Rules to Cloudflare Gateway"]
    types:
      - completed
jobs:
  retry1:
    name: Cloudflare Gateway
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Delay for 60 seconds
        run: sleep 60
        
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Cloudflare Gateway Zero Trust
        run: python -m src
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
          PYTHONDONTWRITEBYTECODE: 1
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1       
